'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Locale
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("GemEvaulatorPortable.Locale", GetType(Locale).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to About.
        '''</summary>
        Friend Shared ReadOnly Property About() As String
            Get
                Return ResourceManager.GetString("About", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to About (&amp;A).
        '''</summary>
        Friend Shared ReadOnly Property AboutMenu() As String
            Get
                Return ResourceManager.GetString("AboutMenu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Always on Top (&amp;T).
        '''</summary>
        Friend Shared ReadOnly Property AlwaysOnTop() As String
            Get
                Return ResourceManager.GetString("AlwaysOnTop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Out of bound value. Double check if the gem type/stat is correct..
        '''</summary>
        Friend Shared ReadOnly Property BadType() As String
            Get
                Return ResourceManager.GetString("BadType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to false.
        '''</summary>
        Friend Shared ReadOnly Property bold() As String
            Get
                Return ResourceManager.GetString("bold", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Got Bugs?.
        '''</summary>
        Friend Shared ReadOnly Property bugText() As String
            Get
                Return ResourceManager.GetString("bugText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Calculate.
        '''</summary>
        Friend Shared ReadOnly Property calculate() As String
            Get
                Return ResourceManager.GetString("calculate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Critical Damage.
        '''</summary>
        Friend Shared ReadOnly Property CD() As String
            Get
                Return ResourceManager.GetString("CD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Critical Hit.
        '''</summary>
        Friend Shared ReadOnly Property CH() As String
            Get
                Return ResourceManager.GetString("CH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Click on the icons below to go to author&apos;s page.
        '''</summary>
        Friend Shared ReadOnly Property Contact() As String
            Get
                Return ResourceManager.GetString("Contact", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Empowered Gem Initial Stat.
        '''</summary>
        Friend Shared ReadOnly Property EGI() As String
            Get
                Return ResourceManager.GetString("EGI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to English (&amp;E).
        '''</summary>
        Friend Shared ReadOnly Property English() As String
            Get
                Return ResourceManager.GetString("English", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Arial.
        '''</summary>
        Friend Shared ReadOnly Property fontFace() As String
            Get
                Return ResourceManager.GetString("fontFace", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 460.
        '''</summary>
        Friend Shared ReadOnly Property formHeight() As String
            Get
                Return ResourceManager.GetString("formHeight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Trove Gem Evaulator Portable.
        '''</summary>
        Friend Shared ReadOnly Property formName() As String
            Get
                Return ResourceManager.GetString("formName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 690.
        '''</summary>
        Friend Shared ReadOnly Property formWidth() As String
            Get
                Return ResourceManager.GetString("formWidth", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property forumIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forumIcon", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to http://forums.trovegame.com/member.php?16006413-Willy_Sunny.
        '''</summary>
        Friend Shared ReadOnly Property forumLink() As String
            Get
                Return ResourceManager.GetString("forumLink", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Current Gem Info.
        '''</summary>
        Friend Shared ReadOnly Property getInfo1() As String
            Get
                Return ResourceManager.GetString("getInfo1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Power Rank.
        '''</summary>
        Friend Shared ReadOnly Property getInfo2() As String
            Get
                Return ResourceManager.GetString("getInfo2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Level.
        '''</summary>
        Friend Shared ReadOnly Property getInfo3() As String
            Get
                Return ResourceManager.GetString("getInfo3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Health Regeneration.
        '''</summary>
        Friend Shared ReadOnly Property HR() As String
            Get
                Return ResourceManager.GetString("HR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Individual Stat.
        '''</summary>
        Friend Shared ReadOnly Property individual() As String
            Get
                Return ResourceManager.GetString("individual", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gem&apos;s Initial Info.
        '''</summary>
        Friend Shared ReadOnly Property initInfo1() As String
            Get
                Return ResourceManager.GetString("initInfo1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gem Type.
        '''</summary>
        Friend Shared ReadOnly Property initInfo2() As String
            Get
                Return ResourceManager.GetString("initInfo2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Initial Stat Count.
        '''</summary>
        Friend Shared ReadOnly Property initInfo3() As String
            Get
                Return ResourceManager.GetString("initInfo3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please enter level 1 gem&apos;s stats.
        '''</summary>
        Friend Shared ReadOnly Property inputInfo1() As String
            Get
                Return ResourceManager.GetString("inputInfo1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stat Value.
        '''</summary>
        Friend Shared ReadOnly Property inputInfo2() As String
            Get
                Return ResourceManager.GetString("inputInfo2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stat Name.
        '''</summary>
        Friend Shared ReadOnly Property inputInfo3() As String
            Get
                Return ResourceManager.GetString("inputInfo3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There&apos;s an error trying to convert your input. Please double check the values.
        '''</summary>
        Friend Shared ReadOnly Property invalidInput() As String
            Get
                Return ResourceManager.GetString("invalidInput", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid level entered. Please re-enter again..
        '''</summary>
        Friend Shared ReadOnly Property invalidLevelInput() As String
            Get
                Return ResourceManager.GetString("invalidLevelInput", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid power rank entered. Please re-enter again..
        '''</summary>
        Friend Shared ReadOnly Property invalidPRInput() As String
            Get
                Return ResourceManager.GetString("invalidPRInput", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Language (&amp;L).
        '''</summary>
        Friend Shared ReadOnly Property Language() As String
            Get
                Return ResourceManager.GetString("Language", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Magic Damage.
        '''</summary>
        Friend Shared ReadOnly Property MD() As String
            Get
                Return ResourceManager.GetString("MD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exit (&amp;X).
        '''</summary>
        Friend Shared ReadOnly Property menuExit() As String
            Get
                Return ResourceManager.GetString("menuExit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Max Health.
        '''</summary>
        Friend Shared ReadOnly Property MH() As String
            Get
                Return ResourceManager.GetString("MH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Evaluator can only calculate level 1 gems..
        '''</summary>
        Friend Shared ReadOnly Property NotLevel1() As String
            Get
                Return ResourceManager.GetString("NotLevel1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Not Level 1.
        '''</summary>
        Friend Shared ReadOnly Property notLevel1Short() As String
            Get
                Return ResourceManager.GetString("notLevel1Short", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Out of Bound.
        '''</summary>
        Friend Shared ReadOnly Property outOfBoundShort() As String
            Get
                Return ResourceManager.GetString("outOfBoundShort", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Physical Damage.
        '''</summary>
        Friend Shared ReadOnly Property PD() As String
            Get
                Return ResourceManager.GetString("PD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to % Max Health.
        '''</summary>
        Friend Shared ReadOnly Property PMH() As String
            Get
                Return ResourceManager.GetString("PMH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Radiant.
        '''</summary>
        Friend Shared ReadOnly Property radiant() As String
            Get
                Return ResourceManager.GetString("radiant", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Report Here!.
        '''</summary>
        Friend Shared ReadOnly Property reportText() As String
            Get
                Return ResourceManager.GetString("reportText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to http://forums.trovegame.com/showthread.php?98537-Stop-Leveling-up-the-wrong-Gem.-Use-the-Evaulator-and-show-off-your-Gem!.
        '''</summary>
        Friend Shared ReadOnly Property reportURL() As String
            Get
                Return ResourceManager.GetString("reportURL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Restart.
        '''</summary>
        Friend Shared ReadOnly Property restart() As String
            Get
                Return ResourceManager.GetString("restart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Result.
        '''</summary>
        Friend Shared ReadOnly Property result() As String
            Get
                Return ResourceManager.GetString("result", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Score.
        '''</summary>
        Friend Shared ReadOnly Property score() As String
            Get
                Return ResourceManager.GetString("score", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Holy crap! Please send a screen shot to willy_sunny@invisiblearea.com..
        '''</summary>
        Friend Shared ReadOnly Property Score1() As String
            Get
                Return ResourceManager.GetString("Score1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Holy crap! Please send a screen shot to willy_sunny@invisiblearea.com..
        '''</summary>
        Friend Shared ReadOnly Property Score100() As String
            Get
                Return ResourceManager.GetString("Score100", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Junkier than junk. Salvage it..
        '''</summary>
        Friend Shared ReadOnly Property Score35() As String
            Get
                Return ResourceManager.GetString("Score35", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Meh, not really worth the cost to level it up..
        '''</summary>
        Friend Shared ReadOnly Property Score45() As String
            Get
                Return ResourceManager.GetString("Score45", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Not too bad, but not too good either..
        '''</summary>
        Friend Shared ReadOnly Property Score55() As String
            Get
                Return ResourceManager.GetString("Score55", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Not a bad gem to hang around..
        '''</summary>
        Friend Shared ReadOnly Property Score75() As String
            Get
                Return ResourceManager.GetString("Score75", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Class A gem! Great find!.
        '''</summary>
        Friend Shared ReadOnly Property Score86() As String
            Get
                Return ResourceManager.GetString("Score86", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wow, a class S gem! Congrats!.
        '''</summary>
        Friend Shared ReadOnly Property Score95() As String
            Get
                Return ResourceManager.GetString("Score95", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Settings (&amp;S).
        '''</summary>
        Friend Shared ReadOnly Property Settings() As String
            Get
                Return ResourceManager.GetString("Settings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Small Gem Evaluator.
        '''</summary>
        Friend Shared ReadOnly Property SGE() As String
            Get
                Return ResourceManager.GetString("SGE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Simplified Chinese (&amp;S).
        '''</summary>
        Friend Shared ReadOnly Property SimplifiedChinese() As String
            Get
                Return ResourceManager.GetString("SimplifiedChinese", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stellar.
        '''</summary>
        Friend Shared ReadOnly Property stellar() As String
            Get
                Return ResourceManager.GetString("stellar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error.
        '''</summary>
        Friend Shared ReadOnly Property titleError() As String
            Get
                Return ResourceManager.GetString("titleError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Total.
        '''</summary>
        Friend Shared ReadOnly Property total() As String
            Get
                Return ResourceManager.GetString("total", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Traditional Chinese (&amp;T).
        '''</summary>
        Friend Shared ReadOnly Property TraditionalChinese() As String
            Get
                Return ResourceManager.GetString("TraditionalChinese", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property TroveSig() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TroveSig", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unknown.
        '''</summary>
        Friend Shared ReadOnly Property unknown() As String
            Get
                Return ResourceManager.GetString("unknown", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
